"""Base adapter contract and shared helpers for the structured observation plane.

Each provider adapter normalizes one agent CLI's transcript into a stream of
:class:`~claude_hub.models.AgentStreamEvent` records. The raw terminal (Layer C)
is always the fail-closed fallback when no adapter can source a transcript.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from ...models import (
    AgentStreamEvent,
    AgentStreamEventType,
    AgentType,
    ManagedSession,
    StreamCapabilities,
)

# Negative-cache window for failed source discovery. Keeps the fail-closed
# capabilities path cheap when an agent hasn't written its transcript yet.
_DISCOVERY_NEGATIVE_TTL_S = 5.0


@dataclass
class _TurnAccumulator:
    """Per-turn accumulated text/thinking for final-snapshot deduplication.

    Providers (Cursor, Claude with ``--include-partial-messages``) emit both
    incremental deltas and a final full-text snapshot of the assistant message.
    Without deduplication the snapshot is appended verbatim and the visible
    text doubles. The accumulator tracks what has already been emitted so the
    snapshot can be reconciled: exact match → skip; strict extension → emit
    only the suffix; otherwise fail closed.
    """

    text: str = ""
    thinking: str = ""


@dataclass
class NormalizeContext:
    """Per-line normalization context carrying session identity and a clock.

    ``turn_id`` is the active user turn's stable id (generated by the frontend
    as ``client_turn_id``). When set, every event the adapter emits for this
    turn is stamped with it so the frontend can upsert by identity. The tailer
    sets it immediately when a user turn is submitted, before the provider
    produces any output.
    """

    session_id: str
    tab_id: str
    agent_type: AgentType
    run_epoch: Optional[int]
    turn_id: Optional[str] = None
    now: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def event(
        self,
        type: AgentStreamEventType,
        payload: Dict[str, Any],
        *,
        call_id: Optional[str] = None,
        message_id: Optional[str] = None,
    ) -> AgentStreamEvent:
        """Build an event pre-populated with this context's identity fields.

        ``turn_id`` is always taken from the context. ``message_id`` defaults
        to a role-suffixed derivative of ``turn_id`` when the caller does not
        supply a provider-native id:

        * ``turn_started`` → ``{turn_id}:user``
        * ``text_delta`` → ``{turn_id}:assistant``
        * ``thinking_delta`` → ``{turn_id}:thinking``
        * ``turn_completed`` → ``{turn_id}`` (the turn itself)
        """
        if message_id is None and self.turn_id:
            if type == AgentStreamEventType.TURN_STARTED:
                message_id = f"{self.turn_id}:user"
            elif type == AgentStreamEventType.TEXT_DELTA:
                message_id = f"{self.turn_id}:assistant"
            elif type == AgentStreamEventType.THINKING_DELTA:
                message_id = f"{self.turn_id}:thinking"
            elif type == AgentStreamEventType.TURN_COMPLETED:
                message_id = self.turn_id
        return AgentStreamEvent(
            stream_sequence=0,  # assigned by the store on append
            session_id=self.session_id,
            tab_id=self.tab_id,
            agent_type=self.agent_type,
            type=type,
            run_epoch=self.run_epoch,
            turn_id=self.turn_id,
            message_id=message_id,
            call_id=call_id,
            payload=payload,
            created_at=self.now,
        )


@dataclass(frozen=True)
class SnapshotRecord:
    """One validated row from an authoritative whole-file transcript.

    ``source_id`` is stable across full-file rewrites and includes the
    managed-session id, canonical row digest, and duplicate occurrence ordinal.
    The tailer persists it so unchanged history is never appended twice.
    """

    source_id: str
    raw: Dict[str, Any]
    # A provider-declared row class used only for narrow reconciliation rules.
    # Empty preserves the conservative generic default.
    source_kind: str = ""


@dataclass(frozen=True)
class TranscriptSnapshot:
    """A bounded, fully validated transcript snapshot."""

    digest: str
    records: Tuple[SnapshotRecord, ...]


class AgentStreamAdapter:
    """Abstract base for provider transcript adapters.

    Subclasses set ``adapter_id``, ``schema_version``, ``supports_approval_ui``,
    and ``supports_tool_timeline``; implement :meth:`discover_source` and
    :meth:`normalize_line`; and may override :meth:`supports_snapshot` /
    :meth:`read_snapshot` for snapshot-style sources (Cursor ACP).
    """

    adapter_id: str = "base"
    schema_version: int = 0
    supports_approval_ui: bool = False
    supports_tool_timeline: bool = False

    def __init__(self) -> None:
        # Per-turn accumulators keyed by (session_id, run_epoch). Used to
        # reconcile final full-text snapshots against already-emitted deltas
        # so the assistant text is never duplicated.
        self._turn_state: Dict[Tuple[str, int], _TurnAccumulator] = {}

    def _turn_key(self, ctx: NormalizeContext) -> Tuple[str, int]:
        epoch = ctx.run_epoch if ctx.run_epoch is not None else 0
        return (ctx.session_id, epoch)

    def _get_turn_state(self, ctx: NormalizeContext) -> _TurnAccumulator:
        key = self._turn_key(ctx)
        state = self._turn_state.get(key)
        if state is None:
            state = _TurnAccumulator()
            self._turn_state[key] = state
        return state

    def _clear_turn_state(self, ctx: NormalizeContext) -> None:
        self._turn_state.pop(self._turn_key(ctx), None)

    def _reconcile_text(self, ctx: NormalizeContext, final_text: str) -> Optional[str]:
        """Reconcile a final full-text snapshot against accumulated deltas.

        Returns the suffix to emit (empty string if the snapshot exactly
        matches accumulated text, meaning nothing new to emit), or ``None`` if
        the snapshot cannot be safely reconciled (caller should fail closed).
        """
        state = self._get_turn_state(ctx)
        if final_text == state.text:
            return ""
        if state.text and final_text.startswith(state.text):
            suffix = final_text[len(state.text) :]
            state.text = final_text
            return suffix
        if not state.text:
            # No deltas were emitted (e.g. provider only sent the final
            # snapshot). Emit the full text.
            state.text = final_text
            return final_text
        # The snapshot neither matches nor extends the accumulated text. This
        # is a genuine inconsistency we cannot safely resolve.
        return None

    def _reconcile_thinking(self, ctx: NormalizeContext, final_thinking: str) -> Optional[str]:
        """Reconcile a final thinking snapshot against accumulated deltas."""
        state = self._get_turn_state(ctx)
        if final_thinking == state.thinking:
            return ""
        if state.thinking and final_thinking.startswith(state.thinking):
            suffix = final_thinking[len(state.thinking) :]
            state.thinking = final_thinking
            return suffix
        if not state.thinking:
            state.thinking = final_thinking
            return final_thinking
        return None

    def capabilities(self, session: ManagedSession) -> StreamCapabilities:
        """Return the capabilities this adapter advertises for ``session``.

        Defaults to ``structured=True`` when a source can be discovered;
        subclasses may override (e.g. Codex waits for its rollout to exist).
        """
        source = discover_source_cached(self, session)
        return StreamCapabilities(
            structured=source is not None,
            adapter_id=self.adapter_id,
            schema_version=self.schema_version,
            sources=[str(source)] if source else [],
            supports_approval_ui=self.supports_approval_ui,
            supports_tool_timeline=self.supports_tool_timeline,
        )

    # ── source discovery ─────────────────────────────────────────────────────

    def discover_source(self, session: ManagedSession) -> Optional[Path]:
        """Locate the transcript file for ``session`` or return ``None``."""
        raise NotImplementedError

    # ── normalization ────────────────────────────────────────────────────────

    def normalize_line(self, raw: Dict[str, Any], ctx: NormalizeContext) -> List[AgentStreamEvent]:
        """Normalize one raw transcript line into zero or more events.

        Must be pure and defensive: skip anything unparseable, never raise.
        """
        raise NotImplementedError

    # ── snapshot support (optional) ──────────────────────────────────────────

    def supports_snapshot(self, session: ManagedSession) -> bool:
        """Whether this adapter reads a full snapshot instead of tailing lines.

        Append-only Claude/Codex sources keep the default ``False``. Cursor's
        interactive transcript can rewrite its JSONL during checkpoint
        compaction, so its adapter opts into snapshot reconciliation.
        """
        return False

    def read_snapshot(self, path: Path, session: ManagedSession) -> TranscriptSnapshot:
        """Return the validated snapshot for snapshot-style sources."""
        raise NotImplementedError


# ── shared discovery helpers ─────────────────────────────────────────────────


@dataclass
class _DiscoveryCacheEntry:
    path: Optional[Path]
    expires_at: float


_discovery_cache: Dict[Tuple[str, str], _DiscoveryCacheEntry] = {}


def discover_source_cached(adapter: AgentStreamAdapter, session: ManagedSession) -> Optional[Path]:
    """Cache :meth:`discover_source` results (including ``None``) briefly."""
    key = (adapter.adapter_id, session.id)
    entry = _discovery_cache.get(key)
    now = time.monotonic()
    if entry is not None and entry.expires_at > now:
        return entry.path
    try:
        path = adapter.discover_source(session)
    except Exception:
        path = None
    _discovery_cache[key] = _DiscoveryCacheEntry(
        path=path, expires_at=now + _DISCOVERY_NEGATIVE_TTL_S
    )
    return path


def invalidate_source(session_id: str) -> None:
    """Drop all cached discovery results for ``session_id`` (e.g. on rotation)."""
    keys = [k for k in _discovery_cache if k[1] == session_id]
    for k in keys:
        _discovery_cache.pop(k, None)


def resolve_process_hint(session: ManagedSession) -> Tuple[str, Optional[str]]:
    """Return ``(cwd, agent_session_id)`` from the live ttyd process, if any."""
    try:
        from ..ttyd_manager import ttyd_manager

        proc = ttyd_manager.processes.get(session.tab_id)
    except Exception:
        proc = None
    cwd = session.workspace_path or ""
    agent_session_id: Optional[str] = None
    if proc is not None:
        proc_cwd = getattr(proc, "cwd", None)
        if proc_cwd:
            cwd = proc_cwd
        proc_session_id = getattr(proc, "agent_session_id", None)
        if proc_session_id:
            agent_session_id = proc_session_id
    if not agent_session_id:
        agent_session_id = session.agent_session_id
    return cwd, agent_session_id


def resolve_cwd(session: ManagedSession) -> str:
    """Prefer the live process cwd; fall back to the session's workspace path."""
    cwd, _ = resolve_process_hint(session)
    return cwd or session.workspace_path or ""
