#!/bin/bash
# Cloudflare Tunnel 初始化脚本
# 用于设置 Cloudflare Tunnel 以实现公网访问

set -e

echo "========================================="
echo "  Claude Hub - Cloudflare Tunnel 设置"
echo "========================================="
echo ""

# 检查 cloudflared 是否安装
if ! command -v cloudflared &> /dev/null; then
    echo "❌ cloudflared 未安装"
    echo ""
    echo "安装方式："
    echo "  macOS:   brew install cloudflare/cloudflare/cloudflared"
    echo "  其他:    https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/"
    echo ""
    exit 1
fi

echo "✅ cloudflared 已安装"
echo ""

# 检查是否已登录
if [ ! -f ~/.cloudflared/cert.pem ]; then
    echo "正在打开浏览器进行 Cloudflare 认证..."
    cloudflared tunnel login
    echo ""
fi

# 创建隧道
TUNNEL_NAME="claude-hub"
echo "创建隧道 '$TUNNEL_NAME'..."

# 检查隧道是否已存在
if cloudflared tunnel list | grep -q "$TUNNEL_NAME"; then
    echo "⚠️  隧道 '$TUNNEL_NAME' 已存在"
    read -p "是否使用现有隧道？(y/n): " use_existing
    if [ "$use_existing" != "y" ]; then
        echo "请删除现有隧道后重新运行: cloudflared tunnel delete $TUNNEL_NAME"
        exit 1
    fi
else
    cloudflared tunnel create "$TUNNEL_NAME"
fi

# 获取隧道信息
TUNNEL_ID=$(cloudflared tunnel list | grep "$TUNNEL_NAME" | awk '{print $1}')
echo ""
echo "✅ 隧道 ID: $TUNNEL_ID"
echo ""

# 询问域名
read -p "请输入要使用的域名 (例如: claude.your-domain.com): " DOMAIN
echo ""

# 配置 DNS 路由
echo "配置 DNS 路由..."
cloudflared tunnel route dns "$TUNNEL_NAME" "$DOMAIN"
echo ""

# 创建配置文件
CONFIG_DIR="$(dirname "$0")/../docker/cloudflared"
mkdir -p "$CONFIG_DIR"
CONFIG_FILE="$CONFIG_DIR/config.yml"

cat > "$CONFIG_FILE" << EOF
# Cloudflare Tunnel Configuration for Claude Hub
# Generated by cloudflared-setup.sh

tunnel: $TUNNEL_ID
credentials-file: $HOME/.cloudflared/$TUNNEL_ID.json

ingress:
  - hostname: $DOMAIN
    service: http://localhost:5173
  - service: http_status:404
EOF

echo "✅ 配置文件已创建: $CONFIG_FILE"
echo ""

# 更新 .env.example 中的 FRONTEND_URL
ENV_EXAMPLE="$(dirname "$0")/../.env.example"
if [ -f "$ENV_EXAMPLE" ]; then
    if grep -q "^FRONTEND_URL=" "$ENV_EXAMPLE"; then
        sed -i.bak "s|^FRONTEND_URL=.*|FRONTEND_URL=https://$DOMAIN|" "$ENV_EXAMPLE"
        rm -f "$ENV_EXAMPLE.bak"
        echo "✅ 已更新 .env.example 中的 FRONTEND_URL"
    fi
fi

echo ""
echo "========================================="
echo "  🎉 设置完成！"
echo "========================================="
echo ""
echo "下一步："
echo "1. 确保 .env 文件中的 FRONTEND_URL=https://$DOMAIN"
echo "2. 启动 Claude Hub 后端和前端"
echo "3. 运行隧道: ./scripts/cloudflared-run.sh"
echo ""
echo "配置文件位置: $CONFIG_FILE"
echo ""
