#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
BACKEND="$ROOT/backend"
FRONTEND="$ROOT/frontend"
PYTHON="${CLAUDE_HUB_E2E_PYTHON:-$BACKEND/.venv/bin/python3}"
SUITE_ROOT="${CLAUDE_HUB_E2E_SUITE_ROOT:-/tmp/claude_hub_agent_tag_e2e}"
HOME_DIR="${CLAUDE_HUB_E2E_HOME:-$SUITE_ROOT/home}"
REPO_DIR="${CLAUDE_HUB_E2E_REPO:-$SUITE_ROOT/repo}"
PORT="${CLAUDE_HUB_E2E_PORT:-19176}"
FRONTEND_PORT="${CLAUDE_HUB_E2E_FRONTEND_PORT:-5176}"
TTYD_BASE="${CLAUDE_HUB_E2E_TTYD_BASE:-19400}"
TMUX_PREFIX="${CLAUDE_HUB_E2E_TMUX_PREFIX:-claude-hub-at-e2e-}"

mkdir -p "$SUITE_ROOT" "$HOME_DIR" "$REPO_DIR"
export CLAUDE_HUB_E2E_SUITE_ROOT="$SUITE_ROOT"
export CLAUDE_HUB_E2E_HOME="$HOME_DIR"
export CLAUDE_HUB_E2E_REPO="$REPO_DIR"
export CLAUDE_HUB_E2E_BACKEND="$BACKEND"
export CLAUDE_HUB_E2E_PYTHON="$PYTHON"
export CLAUDE_HUB_E2E_PORT="$PORT"
export CLAUDE_HUB_E2E_FRONTEND_PORT="$FRONTEND_PORT"
export CLAUDE_HUB_E2E_TTYD_BASE="$TTYD_BASE"
export CLAUDE_HUB_E2E_TMUX_PREFIX="$TMUX_PREFIX"

cd "$FRONTEND"
pnpm build
cd "$ROOT"
exec "$PYTHON" "$ROOT/scripts/task-agent-tag-e2e/run_e2e.py"
