"""Structured agent-stream models (Layer B observation plane).

These provider-neutral records are normalized from agent CLI transcripts,
persisted per session, and exposed by the structured timeline API.
"""

import enum
from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from .schemas import AgentType, StreamCapabilities

__all__ = [
    "AgentStreamEvent",
    "AgentStreamEventType",
    "AgentStreamEventPage",
    "StreamCapabilities",
    "normalize_provider_usage",
]


def normalize_provider_usage(raw: Any, source: str) -> Optional[Dict[str, Any]]:
    """Return the provider-neutral token accounting used by Goal runs.

    Provider releases have used both snake_case and camelCase and sometimes
    nest the counters below ``usage``/``tokenUsage``/``totalTokenUsage``.
    Unknown or malformed counters are ignored; an all-empty record is not
    useful and therefore returns ``None``.
    """
    if not isinstance(raw, dict):
        return None
    candidate = raw
    token_usage = raw.get("tokenUsage")
    if isinstance(token_usage, dict) and isinstance(token_usage.get("last"), dict):
        # Codex notifications contain both cumulative ``total`` and per-turn
        # ``last``. Goal accounting sums turns, so only ``last`` is safe.
        candidate = token_usage["last"]
    for _depth in range(3):
        nested = next(
            (
                candidate[key]
                for key in (
                    "usage",
                    "token_usage",
                    "tokenUsage",
                    "total_token_usage",
                    "totalTokenUsage",
                )
                if isinstance(candidate.get(key), dict)
            ),
            None,
        )
        if nested is None:
            break
        candidate = nested

    def count(*keys: str) -> int:
        for key in keys:
            value = candidate.get(key)
            if isinstance(value, int) and not isinstance(value, bool) and value >= 0:
                return value
        return 0

    input_tokens = count("input", "input_tokens", "inputTokens")
    cached_tokens = count(
        "cached",
        "cached_input_tokens",
        "cachedInputTokens",
        "cache_read_input_tokens",
        "cacheReadInputTokens",
    )
    output_tokens = count("output", "output_tokens", "outputTokens")
    reasoning_tokens = count(
        "reasoning",
        "reasoning_tokens",
        "reasoningTokens",
        "reasoning_output_tokens",
        "reasoningOutputTokens",
    )
    total_tokens = count("total", "total_tokens", "totalTokens")
    if input_tokens or output_tokens:
        total_tokens = max(0, input_tokens - cached_tokens) + output_tokens
    if not any((input_tokens, cached_tokens, output_tokens, reasoning_tokens, total_tokens)):
        return None
    return {
        "input": input_tokens,
        "cached": cached_tokens,
        "output": output_tokens,
        "reasoning": reasoning_tokens,
        "total": total_tokens,
        "source": source,
    }


class AgentStreamEventType(str, enum.Enum):
    """The normalized event types rendered by the structured pane."""

    TURN_STARTED = "turn_started"
    TURN_COMPLETED = "turn_completed"
    TEXT_DELTA = "text_delta"
    THINKING_DELTA = "thinking_delta"
    TOOL_CALL_STARTED = "tool_call_started"
    TOOL_CALL_COMPLETED = "tool_call_completed"
    APPROVAL_REQUIRED = "approval_required"
    APPROVAL_RESOLVED = "approval_resolved"
    ERROR = "error"
    STATUS = "status"


class AgentStreamEvent(BaseModel):
    """One normalized structured-stream event with a session-local cursor.

    ``turn_id`` is the stable identifier for a user turn (generated by the
    frontend as ``client_turn_id`` and echoed back by the tailer). Every event
    belonging to that turn — the user message, assistant text deltas, thinking,
    tool calls, and the terminal ``turn_completed`` — carries the same
    ``turn_id``. This lets the frontend upsert by identity rather than by text
    matching, so two identical user messages remain two distinct turns.

    ``message_id`` identifies a single message within a turn. The user message
    is ``{turn_id}:user``; assistant output is ``{turn_id}:assistant`` (or a
    provider-supplied id when available); thinking is ``{turn_id}:thinking``.
    """

    stream_sequence: int
    session_id: str
    tab_id: str
    agent_type: AgentType
    type: AgentStreamEventType
    run_epoch: Optional[int] = None
    turn_id: Optional[str] = None
    message_id: Optional[str] = None
    call_id: Optional[str] = None
    payload: Dict[str, Any] = Field(default_factory=dict)
    created_at: datetime
    redacted: bool = False


class AgentStreamEventPage(BaseModel):
    """A page of events; ``since_sequence`` is exclusive on reads."""

    events: List[AgentStreamEvent]
    next_sequence: int
    has_more: bool
