"""Structured agent-stream models (Layer B observation plane).

These provider-neutral records are normalized from agent CLI transcripts,
persisted per session, and exposed by the structured timeline API.
"""

import enum
from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from .schemas import AgentType, StreamCapabilities

__all__ = [
    "AgentStreamEvent",
    "AgentStreamEventType",
    "AgentStreamEventPage",
    "StreamCapabilities",
]


class AgentStreamEventType(str, enum.Enum):
    """The normalized event types rendered by the structured pane."""

    TURN_STARTED = "turn_started"
    TURN_COMPLETED = "turn_completed"
    TEXT_DELTA = "text_delta"
    THINKING_DELTA = "thinking_delta"
    TOOL_CALL_STARTED = "tool_call_started"
    TOOL_CALL_COMPLETED = "tool_call_completed"
    APPROVAL_REQUIRED = "approval_required"
    APPROVAL_RESOLVED = "approval_resolved"
    ERROR = "error"
    STATUS = "status"


class AgentStreamEvent(BaseModel):
    """One normalized structured-stream event with a session-local cursor.

    ``turn_id`` is the stable identifier for a user turn (generated by the
    frontend as ``client_turn_id`` and echoed back by the tailer). Every event
    belonging to that turn — the user message, assistant text deltas, thinking,
    tool calls, and the terminal ``turn_completed`` — carries the same
    ``turn_id``. This lets the frontend upsert by identity rather than by text
    matching, so two identical user messages remain two distinct turns.

    ``message_id`` identifies a single message within a turn. The user message
    is ``{turn_id}:user``; assistant output is ``{turn_id}:assistant`` (or a
    provider-supplied id when available); thinking is ``{turn_id}:thinking``.
    """

    stream_sequence: int
    session_id: str
    tab_id: str
    agent_type: AgentType
    type: AgentStreamEventType
    run_epoch: Optional[int] = None
    turn_id: Optional[str] = None
    message_id: Optional[str] = None
    call_id: Optional[str] = None
    payload: Dict[str, Any] = Field(default_factory=dict)
    created_at: datetime
    redacted: bool = False


class AgentStreamEventPage(BaseModel):
    """A page of events; ``since_sequence`` is exclusive on reads."""

    events: List[AgentStreamEvent]
    next_sequence: int
    has_more: bool
